### PR TITLE
[VUE + TS + Quasar] feat: adds single repo api

### PR DESCRIPTION
**Pull request by WillHutt**

### CODE REVIEW

**Review by hdJerry — COMMENTED** [review]
where is this part in the query?

  - [ ] root tree information (folders and files)
   - [ ] readme information

**Comment by WillHutt** [comment]
I just dug deeper and apparently, those are separate queries. I'm in the process of adding them now.

**Comment by hdJerry** [comment]
> I just dug deeper and apparently, those are separate queries. They've been added.

Seen well done, one question
Is there any reason they are all in separate query/ query files?

**Comment by hdJerry** [comment]
> I based it on how the Next version structured it, which has them in separate locations.

Okay, thanks. Got it!

**Review by hdJerry — APPROVED** [review]
LGTM.

**Pull request merged**
