### PR TITLE
[svelte-kit-scss] HTML in README isn't parsing as code block

### LINKED ISSUE #1198: [svelte-kit-scss] HTML in README isn't parsing as code block
Image

### PR DESCRIPTION
**Pull request by kodejuice**
Closes #1198

### CODE REVIEW

**Review by mbicknese — CHANGES_REQUESTED** [review]
This is a good start as it is now no longer showing the raw HTML.

However, the links are getting dropped. I just see the rendered images. Maybe `MarkdownIt` has some safety features which drop a-tags. We might also ask @kenslachtajr whether it's important enough to fix the links.

**Comment by kodejuice** [comment]
> This is a good start as it is now no longer showing the raw HTML.
> 
> However, the links are getting dropped. I just see the rendered images. Maybe `MarkdownIt` has some safety features which drop a-tags. We might also ask @kenslachtajr whether it's important enough to fix the links.

Yes, it needs to be manually added, done that now

**Comment by iansamz** [comment]
This looks OK but I wanted to switch to `mdsvex` as it comes with more benefits: checkout #1240

**Review by iansamz — APPROVED** [review]

**Comment by kodejuice** [comment]
> This looks OK but I wanted to switch to `mdsvex` as it comes with more benefits: checkout #1240

yes i saw that, i think i can close this PR, since `mdsvex` solves both problems

**Pull request closed without merging**
