### PR TITLE
chore: workflow added

### PR DESCRIPTION
**Pull request by hdJerry**
# Setup CI for new project

## Background

We want to review changes in as near real-time as possible. The goal of this is to set up guard rails for development practices and validate features as they’re completed.

## Acceptance

- [x] Setup linting
- [x] Setup Unit testing
- [x] Setup build

## Notes
You can use existing [CI workflows](https://github.com/thisdot/starter.dev-github-showcases/tree/main/.github/workflows) as a baseline

### CODE REVIEW

**Comment by mbicknese** [comment]
Oh wait, it only runs on the main branch! the `path` refers to which files it needs to look at. @hdJerry can you check what happens if we remove the `branches` filter?

**Comment by vyktoremario** [comment]
@hdJerry where are we on this?

**Comment by hdJerry** [comment]
I will revert soon

**Comment by hdJerry** [comment]
I think we have to merge to main to see it it works for other branches, and if it doesn't we can create a ticket to fix.
@vyktoremario @mbicknese

**Review by vyktoremario — APPROVED** [review]

**Pull request merged**
