### PR TITLE
[remix-gql-tailwind] Feature/restructure components

### PR DESCRIPTION
**Pull request by sheerikie**
# What was done?
fixed user profile links to website & twitter AND repo profile URL

# Screenshot/Video/GIF of Changes (if applicable)

TODO: @sheerikie
N/A
Related Ticket(s)

Resolves https://github.com/thisdot/starter.dev-github-showcases/issues/508

### CODE REVIEW

**Review by tyrelchambers — CHANGES_REQUESTED** [review]
Taking a look at the original ticket, I think there are a few more reorganizations we can make.

I would suggest grouping every component folder that starts with `Repo` underneath an overarching "Repositories" or "Repos" folder.

Same thing for every component folder that starts with `User` to put under a `User` folder.

Other folders like Pagination, Icons, and tabNavigation could probably be thrown under a Shared folder.

**Review by tyrelchambers — APPROVED** [review]
Looks good. I don't have any more recommendations as it pertains to the scope of the original ticket. Nice work!

**Review by markshenouda — APPROVED** [review]
LGTM 👍

**Review by tvanantwerp — CHANGES_REQUESTED** [review]
A number of files have broken imports that need to be fixed:

- `app/components/Repositories/RepoAboutWidget/RepoAboutWidget.stories.tsx`
- `app/components/Repositories/RepoActionButtons/RepoActionButtons.stories.tsx`
- `app/components/Repositories/RepoHeader/RepoHeader.stories.tsx`
- `app/components/Repositories/RepoHeading/RepoHeading.stories.tsx`
- `app/components/Repositories/RepoNavigation/RepoNavigation.stories.tsx`

**Pull request closed without merging**
