### PR TITLE
chore: upgrade remix to latest

### PR DESCRIPTION
**Pull request by WillHutt**

### CODE REVIEW

**Review by danecando — CHANGES_REQUESTED** [review]
Can you run the codemod `npx @remix-run/dev migrate` it will automatically fix imports for a change in 1.6.0

**Comment by WillHutt** [comment]
Hmm, I tested everything, it seems fine but I will do so.

**Comment by danecando** [comment]
I think they are going to remove imports from 'remix' in a future update. The codemod changes the imports to explicitly import from each actual package ie `@remix-run/react`

**Review by danecando — APPROVED** [review]
sweet 🚀

**Pull request merged**
