### PR TITLE
solidjs nested file content showing

### PR DESCRIPTION
**Pull request by hdJerry**
# Description 
- clicking into nested files shows blank page, no file contents. Same on main repo page as well as profile page

Image

Image

Image

## Result

Screenshot 2023-01-19 at 10 11 28

### CODE REVIEW

**Review by Megio — COMMENTED** [review]
The code is good and the content of the file is showed, but the header is missing. Probably we can add it in this PR.

**Solid**

Screenshot 2023-01-20 at 09 58 41

**Qwik**

Screenshot 2023-01-20 at 09 58 48

**Review by Megio — COMMENTED** [review]
One last little thing to fix, everything else is great: the "code" tab is not underlined and highlighted when we navigate trough folder or open a file. 

Screenshot 2023-01-23 at 09 26 09

**Comment by hdJerry** [comment]
> One last little thing to fix, everything else is great: the "code" tab is not underlined and highlighted when we navigate trough folder or open a file.
> 
> Screenshot 2023-01-23 at 09 26 09

Yes, i noticed. I sent a message to create another ticket

**Review by Megio — APPROVED** [review]
LGTM

**Pull request merged**
