### PR TITLE
[angular-ngrx-scss] pulls tab

### LINKED ISSUE #834: [Angular - NgRx - SCSS] Pull request page issues
There's a few cleanup tasks needed on this page to get the full expected functionality working.

AC: 
- [ ] Pagination should work - can move to prev / next pages of results, or grayed out if no more results in that direction
- [ ] Page route should be updated to match convention - should be "repoName/pulls" instead of "repoName/pull-requests"
- [ ] Label and sort dropdowns should have data populated from the repo and work

### PR DESCRIPTION
**Pull request by honzikec**
## Checklist

- [x] These changes follow the [contributing guidelines](https://github.com/thisdot/starter.dev-github-showcases/blob/main/CONTRIBUTING.md)
- [x] This fix resolves #834
- [x] I have verified this change works and introduces no additional issues to the best of my knowledge

__To be merged after https://github.com/thisdot/starter.dev-github-showcases/pull/1941__

### CODE REVIEW

**Comment by Megio** [comment]
@honzikec code looks good 🚀 , please check the code smells cause I think they are really easy to solve, also I've just seen that for both issues page and prs pages we don't have the "clear filter button". I don't know if the component is in the scope of these tickets, let me know if you think it could be an easy thing to do or if we will open a new task for it.

**Comment by honzikec** [comment]
> @honzikec code looks good 🚀 , please check the code smells cause I think they are really easy to solve, also I've just seen that for both issues page and prs pages we don't have the "clear filter button". I don't know if the component is in the scope of these tickets, let me know if you think it could be an easy thing to do or if it's better to open a new task for it.

Good catch, @Megio! I've implemented the clear filter button and fixed the lint warnings 👍

**Comment by Megio** [comment]
@honzikec the clear filter button works great! But we still have 2 code smells from SonarCloud. Once fixed the PR LGTM! https://sonarcloud.io/project/issues?id=thisdot_starter.dev-github-showcases&pullRequest=1942&resolved=false&types=CODE_SMELL

**Comment by honzikec** [comment]
> @honzikec the clear filter button works great! But we still have 2 code smells from SonarCloud. Once fixed the PR LGTM! https://sonarcloud.io/project/issues?id=thisdot_starter.dev-github-showcases&pullRequest=1942&resolved=false&types=CODE_SMELL

Oops, I haven't noticed the sonar cloud smells 😅 They should be fixed now, @Megio! Thanks! 🙌

**Review by Megio — APPROVED** [review]

**Pull request merged**
