### PR TITLE
Component/navbar (#124)

### PR DESCRIPTION
**Pull request by AllanJeremy**
Added the `NavHeader` component as well as its related components (`Logo` and `UserAvatar`).

- Added stories for each of the components
- Added unit tests for each of the components
- Added `@pinia/testing` for mock stores when doing unit testing

and probably some other minor details

### CODE REVIEW

**Comment by hdJerry** [comment]
## Stroy Book

For this args to reflect you will need to add each prop in the argTypes.
eg.
```
dark: {}
```

## Worth Nothing
for example, you got a component name as NavBar instead of `<NavBar />` your could do `<nav-bar />`. It makes it steal looks like an HTML tag. You will notice how quasar did theirs too using `<q-bla-bla><q-bla-bla />`

**Comment by AllanJeremy** [comment]
Please clarify on the `dark: {}` part. What component? What does not reflect?
PS, the default `dark` attribute currently works but you can't see the image because it is white against a dark background. Would changing the background when it is dark in storybook help?

## On kebab-case
Got it, thanks. Usually have it as `PascalCase` to distinguish between `CustomComponents` and `framework-components` in an instant.

**Comment by hdJerry** [comment]
> [Vue3 + TS + Quasar] component: Added logo component stories

The logo component story compared to how you did the avatar component story.
Check both argTypes.

**Comment by AllanJeremy** [comment]
Mind if I refactor the `kebab-case` to `PascalCase`?

**Review by hdJerry — APPROVED** [review]

**Comment by hdJerry** [comment]
> Mind if I refactor the `kebab-case` to `PascalCase`?

No need big man

**Comment by AllanJeremy** [comment]
> > Mind if I refactor the `kebab-case` to `PascalCase`?
> 
> No need big man

^ This will be an opensource project, so there probably is one 😅

**Pull request merged**
